export interface ProjectsCommunityI {
  id: number;
  title: string;
  author: string;
  remixes: string;
  category: string;
  image: string;
  featured: boolean;
  createdAt: string;
  likes: number;
  views: number;
  description: string;
  avatar?: string;
}
export const projects = [
  {
    id: 1,
    title: "Batman",
    author: "pixelforge_21",
    remixes: "4241 Remixes",
    category: "Website",
    image: "/community/batman.webp",
    featured: true,
    createdAt: "2023-11-08",
    likes: 8291,
    views: 34819,
    description: "A stylized take on the Dark Knight with a noir atmosphere.",
    avatar: "/avatars/abdul.webp",
  },
  {
    id: 2,
    title: "Circuit EmotioneL par Dr. Mad (2020)",
    author: "noirbits",
    remixes: "3706 Remixes",
    category: "Website",
    image: "/community/circuit_emotionel.webp",
    featured: false,
    createdAt: "2024-04-15",
    likes: 5642,
    views: 21433,
    description: "Experimental digital circuitry inspired by emotional states.",
    avatar: "/avatars/dark.webp",
  },
  {
    id: 3,
    title: "Illustration for Les Echos Weekend",
    author: "le_doodle",
    remixes: "3155 Remixes",
    category: "Website",
    image: "/community/lllustration_echos_weekend.webp",
    featured: true,
    createdAt: "2022-09-21",
    likes: 7102,
    views: 40218,
    description: "Editorial illustration for a French economic magazine.",
  },
  {
    id: 4,
    title: "BTMN - character wip",
    author: "shadecraft",
    remixes: "2557 Remixes",
    category: "Prototype",
    image: "/community/btmn.webp",
    featured: false,
    createdAt: "2023-01-11",
    likes: 4899,
    views: 19884,
    description: "Work-in-progress character model with stylized shading.",
    avatar: "/avatars/dmitry.webp",
  },
  {
    id: 5,
    title: "Just a little something to take the edge off 🚬",
    author: "flatgrain",
    remixes: "2103 Remixes",
    category: "Website",
    image: "/community/just_little_something.webp",
    featured: false,
    createdAt: "2024-06-01",
    likes: 3502,
    views: 17492,
    description: "Moody illustration with dark humor and neon accents.",
  },
  {
    id: 6,
    title: "Design for craft soda",
    author: "cansofpop",
    remixes: "1876 Remixes",
    category: "Personal",
    image: "/community/desing_craft_soda.webp",
    featured: true,
    createdAt: "2021-08-14",
    likes: 9271,
    views: 43726,
    description: "A playful brand identity for a small batch soda company.",
  },
  {
    id: 7,
    title: "Brutalism. Poster 6",
    author: "modulab",
    remixes: "1654 Remixes",
    category: "B2B App",
    image: "/community/brutalism.webp",
    featured: false,
    createdAt: "2023-03-07",
    likes: 3782,
    views: 18213,
    description: "Typographic experiment inspired by brutalist architecture.",
    avatar: "/avatars/iogorilla.webp",
  },
  {
    id: 8,
    title: "Kraken Logo",
    author: "deepblue_ink",
    remixes: "1432 Remixes",
    category: "Consumer App",
    image: "/community/kraken.webp",
    featured: true,
    createdAt: "2022-12-22",
    likes: 8021,
    views: 31987,
    description: "Aggressive sea monster logo for a tech brand.",
    avatar: "/avatars/lisa.webp",
  },
  {
    id: 9,
    title: "Arkansas Airport Chocolate Box packaging illustration",
    author: "packpal",
    remixes: "1389 Remixes",
    category: "Website",
    image: "/community/arkansas_airport.webp",
    featured: false,
    createdAt: "2024-02-10",
    likes: 2775,
    views: 16028,
    description: "Whimsical illustration for local airport chocolate gift box.",
    avatar: "/avatars/mick.webp",
  },
  {
    id: 10,
    title: "Wonder Boy",
    author: "sketchrealm",
    remixes: "1264 Remixes",
    category: "Website",
    image: "/community/wonder_boy.webp",
    featured: true,
    createdAt: "2023-06-19",
    likes: 6663,
    views: 24863,
    description: "Hero concept for an indie platformer project.",
  },
  {
    id: 11,
    title: "Dionysus god of wine",
    author: "vintagevines",
    remixes: "1132 Remixes",
    category: "Personal",
    image: "/community/dionysus_god.webp",
    featured: false,
    createdAt: "2022-04-02",
    likes: 3441,
    views: 13742,
    description: "Mythological reinterpretation of the god of celebration.",
    avatar: "/avatars/petar.webp",
  },
  {
    id: 12,
    title: "Jax Ale Trail - Logo",
    author: "hopworks",
    remixes: "997 Remixes",
    category: "Website",
    image: "/community/jax_ale_trail.webp",
    featured: false,
    createdAt: "2021-12-30",
    likes: 2013,
    views: 10385,
    description: "Custom logo for a craft beer tour in Jacksonville.",
  },
  {
    id: 13,
    title: "Ignite fire 🔥 flame wordmark",
    author: "typoburn",
    remixes: "856 Remixes",
    category: "Website",
    image: "/community/ignite_fire.webp",
    featured: true,
    createdAt: "2023-10-04",
    likes: 7340,
    views: 28110,
    description: "Dynamic wordmark that plays with flame-shaped ligatures.",
    avatar: "/avatars/tommy.webp",
  },
  {
    id: 14,
    title: "Casting Company Logo",
    author: "brandframe",
    remixes: "734 Remixes",
    category: "Website",
    image: "/community/casting_company.webp",
    featured: false,
    createdAt: "2024-01-26",
    likes: 3221,
    views: 14908,
    description: "Sleek logotype for a creative talent casting agency.",
    avatar: "/avatars/valentin.webp",
  },
  {
    id: 15,
    title: "Hi-Lite Drive in",
    author: "Petar Kilibarda",
    remixes: "829 Remixes",
    category: "Website",
    image: "/community/hi_lite.webp",
    featured: false,
    createdAt: "2023-08-12",
    likes: 2891,
    views: 13472,
    description: "Retro signage and drive-in aesthetics brought back to life.",
  },
  {
    id: 16,
    title: "Yoga Logo - Yoga Branding - Print Design",
    author: "Kahaf design agency",
    remixes: "4204 Remixes",
    category: "Website",
    image: "/community/yoga.webp",
    featured: true,
    createdAt: "2024-03-03",
    likes: 6427,
    views: 27534,
    description: "Clean, calming identity work for a wellness yoga brand.",
  },
];
